//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AddressesJsContent
        {
            get
            {
                return ResourceManager.GetString("AddressesJsContent", resourceCulture);
            }
        }

        public static string CustomEmotesJsContent {
            get {
                return ResourceManager.GetString("CustomEmotesJsContent", resourceCulture);
            }
        }
        
        public static string CustomizeProfilesJsContent {
            get {
                return ResourceManager.GetString("CustomizeProfilesJsContent", resourceCulture);
            }
        }
        
        public static string EmotesJsContent {
            get {
                return ResourceManager.GetString("EmotesJsContent", resourceCulture);
            }
        }
        
        public static string GlamoursJsContent {
            get {
                return ResourceManager.GetString("GlamoursJsContent", resourceCulture);
            }
        }
        
        public static string HonorificsJsContent {
            get {
                return ResourceManager.GetString("HonorificsJsContent", resourceCulture);
            }
        }
        
        public static string JobsJsContent {
            get {
                return ResourceManager.GetString("JobsJsContent", resourceCulture);
            }
        }

        public static string MacrosJsContent {
            get {
                return ResourceManager.GetString("MacrosJsContent", resourceCulture);
            }
        }
        
        public static string ModOptionsJsContent {
            get {
                return ResourceManager.GetString("ModOptionsJsContent", resourceCulture);
            }
        }
        
        public static string ModsJsContent {
            get {
                return ResourceManager.GetString("ModsJsContent", resourceCulture);
            }
        }
        
        public static string MoodlesJsContent {
            get {
                return ResourceManager.GetString("MoodlesJsContent", resourceCulture);
            }
        }
        
        public static string OverridesJsContent {
            get {
                return ResourceManager.GetString("OverridesJsContent", resourceCulture);
            }
        }
        
        public static string PluginCollectionsJsContent {
            get {
                return ResourceManager.GetString("PluginCollectionsJsContent", resourceCulture);
            }
        }
    }
}
